projects:
  back:
    schemaPath: back/generated/prisma.graphql
    extensions:
      endpoints:
        default: http://164.132.227.234:4000
  prisma:
    schemaPath: back/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml