projects:
  back:
    schemaPath: back/generated/prisma.graphql
    extensions:
      endpoints:
        default: http://back:4000
  prisma:
    schemaPath: back/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml